### ISSUE TITLE
Block processing stuck on Polkadot CC1

### ISSUE THREAD

**Issue by fgimenez** [polkascan/polkascan-pre-harvester#14]
After completing several items in the block processing queue the process seems to be stuck at #288892:
```
$ curl localhost:8000/queue
{"status": "success", "data": {"harvester_head": 502094, "block_process_queue": [{"from": 241917.0, "to": 288892}]}}
```
New blocks are properly inserted. We are using these settings:
```
- TYPE_REGISTRY=polkadot
- SUBSTRATE_ADDRESS_TYPE=0
- SUBSTRATE_METADATA_VERSION=9
- NEW_SESSION_EVENT_HANDLER=True
- SUBSTRATE_STORAGE_BALANCE=Account
- SUBSTRATE_STORAGE_INDICES=Accounts
- FINALIZATION_ONLY=1
```
We have tried repeatedly to send a `start` request to the API endpoint:
```
$ curl -X POST localhost:8000/start
{"status": "success", "data": {"task_id": "f424b868-c9bb-482b-9e72-f75ee5e42ed1"}}
```
This worked previously when it got stuck on other blocks but now it doesn't seem to work anymore. Also looks like there aren't any errors in the worker logs:
```
[2020-06-30 14:11:21,916: INFO/MainProcess] Received task: app.tasks.accumulate_block_recursive[3a6a7471-7bc8-4e08-aec9-84fabd4cfe0c]  
[2020-06-30 14:11:22,557: WARNING/ForkPoolWorker-2] + Added 0xb2fc2acab3d2120c044119ed55cb65407420a1c23bdc0da074604c4f237f65ac
[2020-06-30 14:11:22,848: WARNING/ForkPoolWorker-2] + Added 0x501a80347741100185549650430625bd0b8ebcf4d7b290ee46fa7dbb9833f83c
[2020-06-30 14:11:22,948: WARNING/ForkPoolWorker-2] . Skipped 0x8aaea2cf4f738f2e0b80d6c694c251a916c9110ffdb939b89726a06f17e5f29b
[2020-06-30 14:11:22,952: INFO/ForkPoolWorker-2] Task app.tasks.accumulate_block_recursive[3a6a7471-7bc8-4e08-aec9-84fabd4cfe0c] succeeded in 1.033748185960576s: {'result': '2 blocks added', 'lastAddedBlockHash': '0x8aaea2cf4f738f2e0b80d6c694c251a916c9110ffdb939b89726a06f17e5f29b', 'sequencerStartedFrom': False}
[2020-06-30 14:11:31,884: INFO/MainProcess] Received task: app.tasks.start_harvester[30d69e38-dbc5-4959-8afd-2b354892b413]  
[2020-06-30 14:11:31,916: INFO/ForkPoolWorker-2] Task app.tasks.start_harvester[30d69e38-dbc5-4959-8afd-2b354892b413] succeeded in 0.030910639907233417s: {'result': 'Harvester job started', 'block_sets': [{'start_block_hash': '0xa98f834cc962f64a27f18047f321f95b07ef7c281742bad925ae71f9f1f053ab', 'end_block_hash': None}], 'sequencer_task_id': '04163218-d3ab-472b-9be0-d82345acfa8d'}
[2020-06-30 14:11:51,901: INFO/MainProcess] Received task: app.tasks.start_sequencer[96ba0455-62ca-49a3-9ec2-5936812b8684]  
[2020-06-30 14:11:55,535: INFO/ForkPoolWorker-2] Task app.tasks.start_sequencer[96ba0455-62ca-49a3-9ec2-5936812b8684] succeeded in 3.6320296940393746s: {'result': 'Block #241917 is missing.. stopping check '}
[2020-06-30 14:12:02,203: INFO/MainProcess] Received task: app.tasks.accumulate_block_recursive[6c2777bf-0dbc-4a22-8143-7d532b5c95aa]  
[2020-06-30 14:12:02,840: WARNING/ForkPoolWorker-2] + Added 0xd6f575ab9f30604ee800fe075ef8ab564264444796a18eac69ac4de10876e4f1
[2020-06-30 14:12:03,145: WARNING/ForkPoolWorker-2] + Added 0x3c6a7ef5aa1477311ed5ca2b05fbf1ffef024ffc21a738e001cce8234718a186
[2020-06-30 14:12:03,168: WARNING/ForkPoolWorker-2] . Skipped 0xe3fd6d576d4bbbc9af3610cad145b756db2ae1a83231439242418edbe81bd4a9
[2020-06-30 14:12:03,171: INFO/ForkPoolWorker-2] Task app.tasks.accumulate_block_recursive[6c2777bf-0dbc-4a22-8143-7d532b5c95aa] succeeded in 0.9668770999414846s: {'result': '2 blocks added', 'lastAddedBlockHash': '0xe3fd6d576d4bbbc9af3610cad145b756db2ae1a83231439242418edbe81bd4a9', 'sequencerStartedFrom': False}
[2020-06-30 14:12:11,885: INFO/MainProcess] Received task: app.tasks.start_harvester[f5ede8a6-8735-4278-b89e-b8a5817977fb]  
[2020-06-30 14:12:11,912: INFO/ForkPoolWorker-2] Task app.tasks.start_harvester[f5ede8a6-8735-4278-b89e-b8a5817977fb] succeeded in 0.025522317038848996s: {'result': 'Harvester job started', 'block_sets': [{'start_block_hash': '0x09eba9988a5ce0ff7bdce6f8cda3b911ed6fb2bc952a08100b1af611ef633630', 'end_block_hash': None}], 'sequencer_task_id': 'ea5ae35e-4851-4a2e-b25f-8eab754085a1'}
[2020-06-30 14:12:31,885: INFO/MainProcess] Received task: app.tasks.start_harvester[3317c00d-4532-4bb2-bb18-ed20f7b30b46]  
[2020-06-30 14:12:31,913: INFO/ForkPoolWorker-2] Task app.tasks.start_harvester[3317c00d-4532-4bb2-bb18-ed20f7b30b46] succeeded in 0.02677196601871401s: {'result': 'Harvester job started', 'block_sets': [{'start_block_hash': '0x5eb837ed5767b37ccf79a68773c02d522aa0474dcaebb63baa259ecd04556694', 'end_block_hash': None}], 'sequencer_task_id': 'ab2c44f0-003f-490b-9fe8-232e7f87e04e'}
[2020-06-30 14:12:51,901: INFO/MainProcess] Received task: app.tasks.start_sequencer[cda8ce54-5606-451c-a762-a2fc170cc35c]  
[2020-06-30 14:12:55,284: INFO/ForkPoolWorker-2] Task app.tasks.start_sequencer[cda8ce54-5606-451c-a762-a2fc170cc35c] succeeded in 3.382033488014713s: {'result': 'Block #241917 is missing.. stopping check '}
[2020-06-30 14:13:11,905: INFO/MainProcess] Received task: app.tasks.start_sequencer[11045c99-fd07-46ee-9744-c36c806cdd3b]  
[2020-06-30 14:13:15,523: INFO/ForkPoolWorker-2] Task app.tasks.start_sequencer[11045c99-fd07-46ee-9744-c36c806cdd3b] succeeded in 3.6170766670256853s: {'result': 'Block #241917 is missing.. stopping check '}
[2020-06-30 14:13:51,903: INFO/MainProcess] Received task: app.tasks.start_sequencer[e3f7138a-612e-43ff-bd31-c88085723a0c]  
[2020-06-30 14:13:55,439: INFO/ForkPoolWorker-2] Task app.tasks.start_sequencer[e3f7138a-612e-43ff-bd31-c88085723a0c] succeeded in 3.5346222911030054s: {'result': 'Block #241917 is missing.. stopping check '}
```

**Comment by fgimenez** [comment]
If I try to process #288892 directly with:
```
curl -X POST -d '{"block_hash": "0xbf48033a449b00806e92fb75153c9d29c013017218d2ee24f0af36b6a5594fe9"}' -H "Content-Type: application/json" localhost:8000/process
```
i get this error on the API:
```
Processing 0xbf48033a449b00806e92fb75153c9d29c013017218d2ee24f0af36b6a5594fe9 ...
Metadata: CACHE MISS 8
[2020-07-01 06:44:45 +0000] [11] [ERROR] Error handling request /process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 395, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Column 'account_id' cannot be null

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 398, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'account_id' cannot be null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 279, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 328, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/usr/src/app/app/resources/harvester.py", line 179, in on_post
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 668, in add_block
    event_processor.accumulation_hook(self.db_session)
  File "/usr/src/app/app/processors/event.py", line 823, in accumulation_hook
    new_account_index_audit.save(db_session)
  File "/usr/src/app/app/models/base.py", line 31, in save
    session.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 398, in cmd_query
    sqlstate=exc.sqlstate)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1048 (23000): Column 'account_id' cannot be null
[SQL: INSERT INTO data_account_index_audit (account_index_id, account_id, block_id, extrinsic_idx, event_idx, type_id) VALUES (%(account_index_id)s, %(account_id)s, %(block_id)s, %(extrinsic_idx)s, %(event_idx)s, %(type_id)s)]
[parameters: {'account_index_id': 10000, 'account_id': None, 'block_id': 288892, 'extrinsic_idx': 2, 'event_idx': 3, 'type_id': 2}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```
Any hints are very appreciated :)

**Comment by arjanz** [comment]
It seemed a DB migration file was missing, which made AccountId nullable, what was the cause of this error when the `IndexFreed` event was triggered in this block. In the next commit I'll add this migration, which will be automatically applied when you restart the harvester. 

Thanks for pointing this out with so much details :)

**Comment by fgimenez** [comment]
Thank you! <3

**Comment by fgimenez** [comment]
All working fine using 85b5a72851fbeb437b718d8a475c08a594f0e49a, thanks! :)
