### ISSUE TITLE
NameError: name 'DemocracyVoteAudit' is not defined

### ISSUE THREAD

**Issue by alanchchen** [polkascan/polkascan-pre-harvester#5]
Hi,

I'm running this harvester to process data in Kusama.

```
[2020-03-24 03:39:34,261: ERROR/ForkPoolWorker-8] Task app.tasks.accumulate_block_recursive[856497f7-efda-4434-a967-5601a25ac7a6] raised unexpected: HarvesterCouldNotAddBlock('0x652741b2ad907604ad5f47e3a6032d25e6baabe674ddd91547ba04cfdc5c709e',)
Traceback (most recent call last):
  File "/usr/src/app/app/tasks.py", line 112, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 564, in add_block
    extrinsic_processor.accumulation_hook(self.db_session)
  File "/usr/src/app/app/processors/extrinsic.py", line 78, in accumulation_hook
    vote_audit = DemocracyVoteAudit(
NameError: name 'DemocracyVoteAudit' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 72, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 139, in accumulate_block_recursive
    raise HarvesterCouldNotAddBlock(block_hash) from exc
```

It seems that `DemocracyVoteAudit` definition is missing.

Here are my environment variables
```
PYTHONPATH=/usr/src/app
SUBSTRATE_RPC_URL=wss://kusama-rpc.polkadot.io/
SUBSTRATE_ADDRESS_TYPE=2    # Kusama
FINALIZATION_ONLY=1
SUBSTRATE_METADATA_VERSION=10
TYPE_REGISTRY=kusama
```

How can I solve the problem?  Thanks

**Comment by arjanz** [comment]
Cleaned up unused extrinsic processor DemocracyVoteAudit for now
